# Generated by Django 3.2.25 on 2024-07-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('dep_svg_path', models.CharField(max_length=255)),
                ('object_relation_matrix', models.TextField()),
            ],
        ),
    ]
