# Generated by Django 3.2.25 on 2024-07-30 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependencydata',
            name='object_relation_matrix',
        ),
        migrations.CreateModel(
            name='RelationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text', models.CharField(max_length=255)),
                ('head_dep', models.CharField(max_length=50)),
                ('dependency_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='analysis.dependencydata')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('dep', models.CharField(max_length=50)),
                ('dependency_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='analysis.dependencydata')),
            ],
        ),
    ]
