# Generated by Django 3.2.25 on 2024-07-30 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20240730_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyDataArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('dep_svg_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleRelationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text', models.CharField(max_length=255)),
                ('head_dep', models.CharField(max_length=50)),
                ('dependency_data_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='analysis.dependencydataarticle')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleObjectData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('dep', models.CharField(max_length=50)),
                ('dependency_data_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='analysis.dependencydataarticle')),
            ],
        ),
    ]
