# Generated by Django 3.2.25 on 2024-07-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_articleobjectdata_articlerelationdata_dependencydataarticle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlerelationdata',
            name='dependency_data_article',
        ),
        migrations.RemoveField(
            model_name='objectdata',
            name='dependency_data',
        ),
        migrations.RemoveField(
            model_name='relationdata',
            name='dependency_data',
        ),
        migrations.AddField(
            model_name='dependencydata',
            name='object_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dependencydata',
            name='relation_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dependencydataarticle',
            name='object_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dependencydataarticle',
            name='relation_data',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='ArticleObjectData',
        ),
        migrations.DeleteModel(
            name='ArticleRelationData',
        ),
        migrations.DeleteModel(
            name='ObjectData',
        ),
        migrations.DeleteModel(
            name='RelationData',
        ),
    ]
