# Generated by Django 3.2.25 on 2024-07-31 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20240730_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyDataExamples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('dep_svg_path', models.CharField(max_length=255)),
                ('object_data', models.JSONField(default=list)),
                ('relation_data', models.JSONField(default=list)),
            ],
        ),
    ]
