sentence_examples = [
    # Simple Sentence (简单句)
    "Birds fly.", "Dogs bark.", "Children laugh.",
    "He sings beautifully.", "She runs fast.", "They play happily.",
    "The baby sleeps soundly every night.", "She dances gracefully on stage.", "He works diligently at the office.",
    "The dog chased the cat.", "She reads books.", "They built a house.",
    "He wrote a letter quickly.", "She painted the fence yesterday.", "They completed the project successfully.",
    "She sent him a letter.", "He gave her a gift.", "They told us a story.",
    "They elected him president.", "She named her cat Whiskers.", "We considered the task difficult.",
    "The sky is blue.", "She is a teacher.", "The cake tastes sweet.",
    "The sky is always blue.", "She is usually busy.", "The cake tastes incredibly sweet.",
    "He runs quickly.", "She sings beautifully.", "They worked hard.",
    "He runs quickly every morning.", "She sings beautifully on stage.", "They worked hard all day.",
    "She sent me a letter.", "He gave her a gift.", "They told us a story.",
    "She sent me a letter yesterday.", "He gave her a gift on her birthday.", "They told us a story during dinner.",
    "They elected him president.", "She named her cat Whiskers.", "We considered the task difficult.",
    "She painted the house yesterday.", "He finished the project on time.", "They left the meeting early.",

    # Compound Sentence (并列句)
    "She likes apples and he likes oranges.", "He sings and she dances.", "The sun rises and the moon sets.",
    "Tom and Jerry are friends.", "Alice and Bob went to the market.", "The dog and the cat played together.",
    "She sings and dances.", "He cooked and cleaned the house.", "They laughed and cried.",
    "She likes apples and oranges.", "He bought a book and a pen.", "They visited Paris and Rome.",
    "You can have tea or coffee.", "We can go to the beach or the park.", "You can study now or later.",
    "Either John or Mary will come.", "You or your brother must attend the meeting.", "Either the cat or the dog made the mess.",
    "You can stay or leave.", "He will either sing or dance.", "They might buy a car or rent one.",
    "She will buy a book or a magazine.", "He wants either coffee or tea.", "They will choose a house or an apartment.",
    "It rained, so we stayed indoors.", "She was tired, so she went to bed early.", "He missed the bus, so he walked home.",
    "It was late, so we left.", "She was hungry, so she ate.", "He was bored, so he read a book.",
    "She worked hard, so she could save money.", "They practiced daily, so they could win the competition.", "He studied well, so he could pass the exam.",
    "It was raining, but they went out anyway.", "He was tired, yet he continued working.", "She was busy, still she helped him.",

    # Complex Sentence (复合句)
    "I was reading when he arrived.", "She left before I could speak to her.", "They waited until the train arrived.",
    "She finished her work before he arrived.", "They left before the meeting ended.", "He called me before I could finish.",
    "I will go out after I finish my work.", "They will leave after the movie ends.", "She will call after she arrives.",
    "She was cooking while he was cleaning.", "They were studying while it was raining.", "He was reading while she was knitting.",
    "If it rains, we will cancel the picnic.", "You can go out as long as you finish your homework.", "Provided that he agrees, we can proceed.",
    "If you study, you will pass.", "If it rains, we will stay inside.", "If you hurry, you will catch the bus.",
    "If I were rich, I would travel the world.", "If he were here, he would help.", "If they had known, they would have come.",
    "If it rains and if it is cold, we will stay home.", "If you study hard and if you listen in class, you will succeed.", "If he calls and if he agrees, we can start the project.",
    "She was happy because she passed the exam.", "He didn't go to school since he was sick.", "They left early as they had another appointment.",
    "He was late because he missed the bus.", "She smiled because she was happy.", "They left because the show was over.",
    "She was tired because she worked all day and because she didn't sleep well.", "He was upset because he lost his wallet and because he missed his train.", "They were happy because they won the game and because they received a prize.",
    "She was promoted because she worked hard and because she showed great leadership.", "He was fined because he parked illegally and because he didn't pay the meter.", "They succeeded because they planned well and because they executed flawlessly.",
    "He studied hard so that he could pass the exam.", "She whispered in order that no one could hear her.", "They left early to avoid the traffic.",
    "He saved money so that he could buy a car.", "She practiced daily in order to improve her skills.", "They moved closer to the city to reduce commute time.",
    "She worked hard to earn money and to gain experience.", "He trained daily to build strength and to increase endurance.", "They studied diligently to pass exams and to secure scholarships.",
    "She saved money to buy a house and to invest in her future.", "He practiced daily to win the championship and to achieve his dreams.", "They relocated to the city to access better education and to improve their living standards.",
    "Although it was raining, they went for a walk.", "Even though he was tired, he continued working.", "Though she was busy, she made time for her friends.",
    "Although it was late, they continued working.", "Even though he was sick, he went to work.", "Though she was tired, she finished her work.",
    "Although it was raining and although it was cold, they went for a walk.", "Even though he was busy and even though he was tired, he helped them.", "Though she was sick and though she was tired, she attended the meeting.",
    "Although it was raining and although it was cold, they went for a walk because they needed fresh air.", "Even though he was busy and even though he was tired, he helped them because they needed support.", "Though she was sick and though she was tired, she attended the meeting because it was important.",
    "He was so tired that he fell asleep immediately.", "She was such a good student that she won a scholarship.", "The noise was so loud that it woke everyone up.",
    "He was so hungry that he ate everything.", "She was so excited that she couldn't sleep.", "They were so late that they missed the show.",
    "He was so tired and so hungry that he fell asleep immediately.", "She was so happy and so excited that she called everyone.", "They were so late and so unprepared that they failed the test.",
    "He was so tired and so hungry that he fell asleep immediately and missed dinner.", "She was so happy and so excited that she called everyone and threw a party.", "They were so late and so unprepared that they failed the test and had to retake it.",
    "He talks as if he knows everything.", "She acted as though nothing had happened.", "They plan their schedule like professionals.",
    "He works as if he were a machine.", "She sings as if she were a bird.", "They play as if they were professionals.",
    "He talks as if he knows everything and as if he were the boss.", "She acted as though nothing had happened and as if she didn't care.", "They plan their schedule like professionals and like they have done it for years.",
    "He talks as if he knows everything and as if he were the boss, even though he is new.", "She acted as though nothing had happened and as if she didn't care, despite being involved.", "They plan their schedule like professionals and like they have done it for years, although they just started.",

    # Compound-Complex Sentence (复合并列句)
    "I was reading when he arrived, and then we had dinner.", "She was cooking while he was cleaning, and they finished together.", "They were watching TV when the power went out, but it came back soon.",
    "I was studying when the phone rang, because I had an exam.", "She was working when he called, because she had a deadline.", "They were eating when the guests arrived, because they were hungry.",
    "I was reading when he arrived, if he is late, I will leave.", "She was cooking while he was cleaning, if they finish, they can rest.", "They were watching TV when the power went out, if it doesn't come back, we will go out.",
    "I was reading when he arrived, although I was tired.", "She was cooking while he was cleaning, even though they were tired.", "They were watching TV when the power went out, although they knew it might happen.",
    "If it rains, we will cancel the picnic, but we can still watch a movie at home.", "If he finishes his work, he can join us, and we will wait for him.", "You can go out if you finish your homework, or you can stay in and relax.",
    "If it rains, we will stay inside, and we will play games.", "If he finishes his work, he can rest, and he can watch TV.", "You can go out if you finish your homework, or you can stay in and read a book.",
    "If it rains, we will stay inside, so that we can stay dry.", "If he finishes his work, he can rest, so that he can be refreshed.", "You can go out if you finish your homework, so that you can enjoy your time.",
    "If it rains, we will stay inside, as if we are in a cozy cabin.", "If he finishes his work, he can rest, like a king on his throne.", "You can go out if you finish your homework, as if you have no worries.",
    "She was happy because she passed the exam, and she celebrated with her friends.", "He was late because he missed the bus, but he still managed to catch the meeting.", "They were tired because they had worked all day, so they decided to rest.",
    "She was happy because she passed the exam, and she received a gift.", "He was late because he missed the bus, so he took a taxi.", "They were tired because they had worked all day, and they went to bed early.",
    "She was happy because she passed the exam, although she had been worried.", "He was late because he missed the bus, even though he left early.", "They were tired because they had worked all day, although they had taken breaks.",
    "She was happy because she passed the exam, if she hadn't, she would have been sad.", "He was late because he missed the bus, if he had taken a taxi, he would have been on time.", "They were tired because they had worked all day, if they hadn't, they would have been energetic.",

    # Special Sentence (特殊句型)
    "The book was read by the teacher.", "The cake was eaten by the children.", "The house was built by the workers.",
    "The book was read by the teacher when the class started.", "The cake was eaten by the children before dinner.", "The house was built by the workers after the foundation was laid.",
    "The book was read by the teacher if it was available.", "The cake was eaten by the children if they were hungry.", "The house was built by the workers if the materials arrived.",
    "The book was read by the teacher because it was important.", "The cake was eaten by the children because it was delicious.", "The house was built by the workers because it was needed.",
    "What did you eat?", "Where are you going?", "Why did she leave?",
    "Did you eat?", "Are you going?", "Did she leave?",
    "How did you eat?", "When are you going?", "How did she leave?",
    "Do you know what he ate?", "Can you tell me where you are going?", "Do you know why she left?",
    "Please open the window.", "Do your homework.", "Close the door.",
    "Don't open the window.", "Don't forget your homework.", "Don't close the door.",
    "Do open the window.", "Please do your homework.", "Do close the door.",
    "Let's open the window.", "Let's do our homework.", "Let's close the door.",
    "What a beautiful day!", "How wonderful!", "What an amazing performance!",
    "What a very beautiful day!", "How incredibly wonderful!", "What an absolutely amazing performance!",
    "What a beautiful day it is!", "How wonderful you are!", "What an amazing performance you gave!",
    "I can't believe what a beautiful day it is!", "You won't believe how wonderful it was!", "They don't know what an amazing performance they gave!",

    # Modifiers (修饰语)
    "The big dog barked.", "A beautiful garden.", "An interesting book.",
    "The big, brown dog barked.", "A beautiful, well-maintained garden.", "An interesting, informative book.",
    "The dog with the big ears barked.", "A garden full of flowers.", "A book about history.",
    "The dog that is big barked.", "A garden that is beautiful.", "A book that is interesting.",
    "She quickly ran.", "He speaks fluently.", "They worked diligently.",
    "She ran very quickly.", "He speaks extremely fluently.", "They worked incredibly diligently.",
    "She ran as fast as she could.", "He speaks like a native.", "They worked without stopping.",
    "She ran until she was exhausted.", "He speaks as if he were a professor.", "They worked as though their lives depended on it.",

    # Complex Clause (复杂从句)
    "The book that you gave me is interesting.", "She is the girl who won the prize.", "This is the house where I grew up.",
    "The book that you gave me is interesting.", "She is the girl who won the prize.", "This is the house where I grew up.",
    "The book, which you gave me, is interesting.", "She, who won the prize, is my friend.", "This house, where I grew up, is old.",
    "The book that you gave me, which is on the table, is interesting.", "She is the girl who won the prize, which is a big honor.", "This is the house where I grew up, which has a big garden.",
    "The fact that she won surprised everyone.", "The idea that he proposed was brilliant.", "The news that he was leaving shocked us all.",
    "The fact that she won surprised everyone.", "The idea that he proposed was brilliant.", "The news that he was leaving shocked us all.",
    "The fact, that she won, surprised everyone.", "The idea, that he proposed, was brilliant.", "The news, that he was leaving, shocked us all.",
    "The fact that she won, which was unexpected, surprised everyone.", "The idea that he proposed, which is innovative, was brilliant.", "The news that he was leaving, which we didn't expect, shocked us all.",
    "I believe that he is honest.", "What he said was surprising.", "She wondered whether it was true.",
    "That she won surprised everyone.", "What he said shocked us.", "Whether it will rain is unknown.",
    "I believe that he is honest.", "She said that she was tired.", "We know that they are coming.",
    "The fact is that she won.", "My belief is that he is honest.", "The question is whether it will rain.",

    # Complex-Compound Clause (复合从句)
    "I was reading the book that you gave me when he arrived.", "She was writing the letter which I asked her to when the phone rang.", "They were discussing the project that they had worked on when the meeting ended.",
    "I was reading the book that you gave me when he arrived.", "She was writing the letter which I asked her to when the phone rang.", "They were discussing the project that they had worked on when the meeting ended.",
    "I was reading the book, which you gave me, when he arrived.", "She was writing the letter, which I asked her to, when the phone rang.", "They were discussing the project, which they had worked on, when the meeting ended.",
    "I was reading the book that you gave me, which is very interesting, when he arrived.", "She was writing the letter which I asked her to, which is very important, when the phone rang.", "They were discussing the project that they had worked on, which is very challenging, when the meeting ended.",
    "If you study hard, even though it is difficult, you will succeed.", "Provided that you attend the meeting, although it is far away, you will learn a lot.", "You can join us if you want, despite being tired.",
    "If you study hard, even though it is difficult, you will succeed.", "Provided that you attend the meeting, although it is far away, you will learn a lot.", "You can join us if you want, despite being tired.",
    "If you study hard, even though it is difficult and time-consuming, you will succeed.", "Provided that you attend the meeting, although it is far away and inconvenient, you will learn a lot.", "You can join us if you want, despite being tired and busy.",
    "If you study hard, even though it is difficult and time-consuming, you will succeed because you are determined.", "Provided that you attend the meeting, although it is far away and inconvenient, you will learn a lot because it is informative.", "You can join us if you want, despite being tired and busy, because we need your help.",

    # Compound Complex Sentence (并列复合句)
    "If it rains, we will cancel the picnic, and if it is sunny, we will go hiking.", "If he comes, we will start the meeting, and if he doesn't, we will wait.", "You can stay if you like, or you can leave if you prefer.",
    "If it rains, we will cancel the picnic, and if it is sunny, we will go hiking.", "If he comes, we will start the meeting, and if he doesn't, we will wait.", "You can stay if you like, or you can leave if you prefer.",
    "If I were rich, I would travel the world, and if I were young, I would learn new languages.", "If he were here, he would help, and if he were healthy, he would join us.", "If they had known, they would have come, and if they had been informed, they would have prepared.",
    "If it rains and if it is cold, we will stay home, and if it is sunny, we will go hiking.", "If you study hard and if you listen in class, you will succeed, and if you practice, you will excel.", "If he calls and if he agrees, we can start the project, and if he doesn't, we will postpone it.",

    # Compound Clauses (并列从句)
    "The book that you gave me and the pen that he lent me are both useful.", "The car that he bought and the house that she rented are both expensive.", "The project that they completed and the report that they submitted are impressive.",
    "The book that you gave me and the pen that he lent me are both useful.", "The car that he bought and the house that she rented are both expensive.", "The project that they completed and the report that they submitted are impressive.",
    "The book, which you gave me, and the pen, which he lent me, are both useful.", "The car, which he bought, and the house, which she rented, are both expensive.", "The project, which they completed, and the report, which they submitted, are impressive.",
    "The book that you gave me, which is very interesting, and the pen that he lent me, which is very expensive, are both useful.", "The car that he bought, which is very fast, and the house that she rented, which is very spacious, are both expensive.", "The project that they completed, which was very challenging, and the report that they submitted, which was very detailed, are impressive.",
    "I believe that he is honest and that she is reliable.", "She knows what he did and why he did it.", "They understand how it works and how to fix it.",
    "That she won and that he lost surprised everyone.", "What he said and what she did shocked us.", "Whether it will rain and whether it will snow is unknown.",
    "I believe that he is honest and that she is reliable.", "She knows what he did and why he did it.", "They understand how it works and how to fix it.",
    "The fact is that she won and that he lost.", "My belief is that he is honest and that she is reliable.", "The question is whether it will rain and whether it will snow.",

    # Modifiers + Complex Sentence (修饰语 + 复合句)
    "The old man who lives next door is very friendly.", "The beautiful garden that we visited yesterday is well-maintained.", "The interesting book that you recommended is a best-seller.",
    "The old, wise man who lives next door is very friendly.", "The beautiful, well-maintained garden that we visited yesterday is well-maintained.", "The interesting, informative book that you recommended is a best-seller.",
    "The man with the big ears who lives next door is very friendly.", "The garden full of flowers that we visited yesterday is well-maintained.", "The book about history that you recommended is a best-seller.",
    "The man who is old and wise who lives next door is very friendly.", "The garden that is beautiful and well-maintained that we visited yesterday is well-maintained.", "The book that is interesting and informative that you recommended is a best-seller.",

    # Complex Modifiers (复杂修饰语)
    "The big brown dog barked.", "A tall, dark, and handsome man entered the room.", "An old, dilapidated house stood at the end of the street.",
    "The dog with the big ears and brown fur barked.", "A man with tall stature and dark hair entered the room.", "A house with old walls and a dilapidated roof stood at the end of the street.",
    "The dog that is big and brown barked.", "A man who is tall and dark entered the room.", "A house that is old and dilapidated stood at the end of the street.",
    "The big, brown dog with the loud bark barked.", "A tall, dark man with the deep voice entered the room.", "An old, dilapidated house with the broken windows stood at the end of the street.",
    "She ran very quickly.", "He speaks extremely fluently.", "They worked incredibly diligently.",
    "She ran as fast as she could very quickly.", "He speaks like a native extremely fluently.", "They worked without stopping incredibly diligently.",
    "She ran until she was exhausted very quickly.", "He speaks as if he were a professor extremely fluently.", "They worked as though their lives depended on it incredibly diligently.",
    "She ran very quickly as fast as she could.", "He speaks extremely fluently like a native.", "They worked incredibly diligently without stopping.",

    # Compound-Complex Relative Clauses (并列复合从句)
    "I was reading the book that you gave me when he arrived, and she was watching TV when her phone rang.", "He was cooking dinner when I called, and she was cleaning the house when we arrived.", "They were playing soccer when it started to rain, and we were hiking when the storm hit.",
    "I was reading the book that you gave me when he arrived, and she was watching TV when her phone rang.", "He was cooking dinner when I called, and she was cleaning the house when we arrived.", "They were playing soccer when it started to rain, and we were hiking when the storm hit.",
    "I was reading the book, which you gave me, when he arrived, and she was watching TV, which was very interesting, when her phone rang.", "He was cooking dinner, which was very delicious, when I called, and she was cleaning the house, which was very dirty, when we arrived.", "They were playing soccer, which was very fun, when it started to rain, and we were hiking, which was very challenging, when the storm hit.",
    "I was reading the book that you gave me, which is very interesting, when he arrived, and she was watching TV, which was very interesting, when her phone rang.", "He was cooking dinner, which was very delicious, when I called, and she was cleaning the house, which was very dirty, when we arrived.", "They were playing soccer, which was very fun, when it started to rain, and we were hiking, which was very challenging, when the storm hit.",

    # Nested Clauses (嵌套从句)
    "I was reading when he arrived while it was raining.", "She was cooking dinner when the phone rang while the children were playing outside.", "They were hiking when it started raining while we were waiting in the car.",
    "I was reading when he arrived while it was raining.", "She was cooking dinner when the phone rang while the children were playing outside.", "They were hiking when it started raining while we were waiting in the car.",
    "I was reading when he arrived while it was raining, which made it hard to concentrate.", "She was cooking dinner when the phone rang while the children were playing outside, which distracted her.", "They were hiking when it started raining while we were waiting in the car, which made it uncomfortable.",
    "I was reading when he arrived while it was raining, and she was watching TV when her phone rang.", "She was cooking dinner when the phone rang while the children were playing outside, and he was working when his boss called.", "They were hiking when it started raining while we were waiting in the car, and we were driving when the storm hit.",
    "If you come early, and if the weather is good, we will go hiking.", "If he finishes his work, and if he has time, he will join us for dinner.", "If you complete your tasks, and if you have no other obligations, you can leave early.",
    "If you come early, and if the weather is good, we will go hiking.", "If he finishes his work, and if he has time, he will join us for dinner.", "If you complete your tasks, and if you have no other obligations, you can leave early.",
    "If you come early, and if the weather is good, we will go hiking, and if it rains, we will stay inside.", "If he finishes his work, and if he has time, he will join us for dinner, and if he doesn't, we will wait.", "If you complete your tasks, and if you have no other obligations, you can leave early, and if you don't, you will have to stay late.",
    "If you come early, and if the weather is good, we will go hiking, and if it rains, we will stay inside, and if it is cold, we will have hot chocolate.", "If he finishes his work, and if he has time, he will join us for dinner, and if he doesn't, we will wait, and if he is late, we will start without him.", "If you complete your tasks, and if you have no other obligations, you can leave early, and if you don't, you will have to stay late, and if you finish later, you can still leave early.",
    "She was happy because she passed the exam which was very difficult.", "He was upset because he missed the bus which was his only means of transportation.", "They were excited because they won the competition which was very challenging.",
    "She was happy because she passed the exam which was very difficult.", "He was upset because he missed the bus which was his only means of transportation.", "They were excited because they won the competition which was very challenging.",
    "She was happy because she passed the exam which was very difficult and she had studied for months.", "He was upset because he missed the bus which was his only means of transportation and he had no money for a taxi.", "They were excited because they won the competition which was very challenging and they had trained hard.",
    "She was happy because she passed the exam which was very difficult and she had studied for months, and because she received a high grade.", "He was upset because he missed the bus which was his only means of transportation and he had no money for a taxi, and because he was late for an important meeting.", "They were excited because they won the competition which was very challenging and they had trained hard, and because they received a big trophy.",

    # Compound Complex Modifiers (复合修饰语)
    "The old, wise man who lives next door is very friendly.", "The large, ancient tree that stands in the park is beautiful.", "The small, cozy cafe that we visited yesterday is charming.",
    "The old man with the big ears who lives next door is very friendly.", "The large tree with the strong branches that stands in the park is beautiful.", "The small cafe with the cozy atmosphere that we visited yesterday is charming.",
    "The old man who is wise and lives next door is very friendly.", "The large tree that is ancient and stands in the park is beautiful.", "The small cafe that is cozy and we visited yesterday is charming.",
    "The old, wise man with the big ears who lives next door is very friendly.", "The large, ancient tree with the strong branches that stands in the park is beautiful.", "The small, cozy cafe with the warm atmosphere that we visited yesterday is charming.",
    "She quickly ran when she saw the dog.", "He calmly spoke when the meeting started.", "They quietly left when the party ended.",
    "She quickly and quietly ran when she saw the dog.", "He calmly and confidently spoke when the meeting started.", "They quietly and swiftly left when the party ended.",
    "She ran as fast as she could when she saw the dog.", "He spoke like a leader when the meeting started.", "They left without a sound when the party ended.",
    "She ran until she was exhausted when she saw the dog.", "He spoke as if he were a leader when the meeting started.", "They left as though they had something to hide when the party ended.",

    # Compound-Complex Concessive Clauses (并列嵌套从句)
    "I was reading the book that you gave me when he arrived, and she was watching TV when her phone rang.", "He was cooking dinner when I called, and she was cleaning the house when we arrived.", "They were playing soccer when it started to rain, and we were hiking when the storm hit.",
    "I was reading the book that you gave me when he arrived, and she was watching TV when her phone rang.", "He was cooking dinner when I called, and she was cleaning the house when we arrived.", "They were playing soccer when it started to rain, and we were hiking when the storm hit.",
    "I was reading the book, which you gave me, when he arrived, and she was watching TV, which was very interesting, when her phone rang.", "He was cooking dinner, which was very delicious, when I called, and she was cleaning the house, which was very dirty, when we arrived.", "They were playing soccer, which was very fun, when it started to rain, and we were hiking, which was very challenging, when the storm hit.",
    "I was reading the book that you gave me, which is very interesting, when he arrived, and she was watching TV, which was very interesting, when her phone rang.", "He was cooking dinner, which was very delicious, when I called, and she was cleaning the house, which was very dirty, when we arrived.", "They were playing soccer, which was very fun, when it started to rain, and we were hiking, which was very challenging, when the storm hit.",

    # Nested Complex Clauses (嵌套复合从句)
    "She was happy because she passed the exam, and if she continues to work hard, she will succeed further.", "He was relieved because he finished the project, and if he submits it on time, he will get a bonus.", "They were satisfied because they completed the task, and if they maintain this level of performance, they will be promoted.",
    "She was happy because she passed the exam, and if she continues to work hard, she will succeed further.", "He was relieved because he finished the project, and if he submits it on time, he will get a bonus.", "They were satisfied because they completed the task, and if they maintain this level of performance, they will be promoted.",
    "She was happy because she passed the exam and received a high grade, and if she continues to work hard, she will succeed further.", "He was relieved because he finished the project and met all the requirements, and if he submits it on time, he will get a bonus.", "They were satisfied because they completed the task and exceeded expectations, and if they maintain this level of performance, they will be promoted.",
    "She was happy because she passed the exam and received a high grade, and because she studied hard, and if she continues to work hard, she will succeed further.", "He was relieved because he finished the project and met all the requirements, and because he worked efficiently, and if he submits it on time, he will get a bonus.", "They were satisfied because they completed the task and exceeded expectations, and because they worked as a team, and if they maintain this level of performance, they will be promoted.",

    # Mixed Sentence (混合句型)
    "The book that was given to me by the teacher when I was in school is very interesting.", "The house that was built by my grandfather when he was young is still standing.", "The cake that was baked by my mother when I was a child was delicious.",
    "The book that was given to me by the teacher when I was in school is very interesting.", "The house that was built by my grandfather when he was young is still standing.", "The cake that was baked by my mother when I was a child was delicious.",
    "The book that was given to me by the teacher when I was in school and when I was in need of guidance is very interesting.", "The house that was built by my grandfather when he was young and when he was full of dreams is still standing.", "The cake that was baked by my mother when I was a child and when I was celebrating my birthday was delicious.",
    "The book that was given to me by the teacher when I was in school, which I attended every day, is very interesting.", "The house that was built by my grandfather when he was young, which he cherished dearly, is still standing.", "The cake that was baked by my mother when I was a child, which I loved very much, was delicious.",

    # Multiple Modifiers (多重修饰语)
    "The quick, agile fox jumps over the lazy dog while the sun is setting.", "The tall, dark man walked swiftly down the street as the evening approached.", "The old, wise woman spoke softly when the children gathered around her.",
    "The quick, agile, cunning fox jumps over the lazy, sleepy dog while the sun is setting, which was a beautiful sight.", "The tall, dark, handsome man walked swiftly, confidently down the street as the evening approached, which made him look mysterious.", "The old, wise, kind woman spoke softly, gently when the children gathered around her, which made them feel comforted.",
    "The fox with the quick, agile movements jumps over the dog with the lazy, sleepy demeanor while the sun is setting, which was a beautiful sight.", "The man with the tall, dark appearance walked with swift, confident steps down the street as the evening approached, which made him look mysterious.", "The woman with the old, wise face spoke with soft, gentle words when the children gathered around her, which made them feel comforted.",
    "The fox that is quick and agile jumps over the dog that is lazy and sleepy while the sun is setting, which was a beautiful sight.", "The man who is tall and dark walked swiftly and confidently down the street as the evening approached, which made him look mysterious.", "The woman who is old and wise spoke softly and gently when the children gathered around her, which made them feel comforted.",

    # Nested Complex Clauses (嵌套复合从句)
    "She was happy because she passed the exam which was very difficult, and she celebrated with her friends who had also done well.", "He was upset because he missed the bus which was his only means of transportation, and he had to walk home which took a long time.", "They were excited because they won the competition which was very challenging, and they received a trophy which was very impressive.",
    "She was happy because she passed the exam which was very difficult, and she celebrated with her friends who had also done well.", "He was upset because he missed the bus which was his only means of transportation, and he had to walk home which took a long time.", "They were excited because they won the competition which was very challenging, and they received a trophy which was very impressive.",
    "She was happy because she passed the exam which was very difficult and she had studied hard, and she celebrated with her friends who had also done well and who were very proud of her.", "He was upset because he missed the bus which was his only means of transportation and he had no money for a taxi, and he had to walk home which took a long time and was very tiring.", "They were excited because they won the competition which was very challenging and they had trained hard, and they received a trophy which was very impressive and well-deserved.",
    "She was happy because she passed the exam which was very difficult and she had studied hard, and because she received a high grade, and she celebrated with her friends who had also done well and who were very proud of her.", "He was upset because he missed the bus which was his only means of transportation and he had no money for a taxi, and because he was late for an important meeting, and he had to walk home which took a long time and was very tiring.", "They were excited because they won the competition which was very challenging and they had trained hard, and because they received a big trophy, and they celebrated with their coach who had supported them and who was very happy."
]
